### ISSUE TITLE
Move static files from WebsiteEditor to WebsiteProvider

### ISSUE THREAD

**Issue by warpech** [StarcounterApps/Website#141]
### Steps to reproduce

1. Start KitchenSink (`a0c8513`), WebsiteEditor, WebsiteProvider (d7b875f)
2. Stop WebsiteEditor
3. Go to `localhost:8080/kitchensink`

### Expected result

You should see KitchenSink wrapped in the DefaultSurface

### Actual result

You get an exception because the static files are missing.

The static files should be moved from WebsiteEditor to WebsiteProvider.

```txt
System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.
Parameter name: Can not find referenced Html file: "/Websiteeditor/surfaces/DefaultSurface.html"
   at Starcounter.HtmlFromJsonProvider.ProvideFromFilePath[T](String filePath) in C:\TeamCity\TeamCity10\buildAgent\work\sc-6455\Level1\src\Starcounter\Middleware\HtmlFromJsonProvider.cs:line 58
   at Starcounter.HtmlFromJsonProvider.Invoke(MimeProviderContext context, Action next) in C:\TeamCity\TeamCity10\buildAgent\work\sc-6455\Level1\src\Starcounter\Middleware\HtmlFromJsonProvider.cs:line 52
   at Starcounter.Internal.JsonMimeConverter.Convert(Request request, IResource before, MimeType mimeType, MimeType& resultingMimeType) in C:\TeamCity\TeamCity10\buildAgent\work\sc-6455\Level1\src\Starcounter.Apps.JsonPatch\BuiltInRestHandlers\JsonMimeConverter.cs:line 18
   at Starcounter.Json.AsMimeType(MimeType mimeType, MimeType& resultingMimeType, Request request) in C:\TeamCity\TeamCity10\buildAgent\work\sc-6455\Level1\src\Starcounter.XSON\Class Json\Json.IResource.cs:line 45
   at Starcounter.Response.ConstructFromFields(Request req, Byte[] givenBuffer) in C:\TeamCity\TeamCity10\buildAgent\work\sc-6455\Level1\src\Starcounter.Internal\Http\Response.cs:line 809
   at Starcounter.Request.SendResponse(Response resp, Byte[] serializationBuf) in C:\TeamCity\TeamCity10\buildAgent\work\sc-6455\Level1\src\Starcounter.Internal\Http\Request.cs:line 1241
   at Starcounter.Internal.AppsBootstrapper.ProcessExternalRequest(Request req) in C:\TeamCity\TeamCity10\buildAgent\work\sc-6455\Level1\src\Starcounter.Apps.JsonPatch\AppsBootstrapper.cs:line 810
ParamName=Can not find referenced Html file: "/Websiteeditor/surfaces/DefaultSurface.html"
HResult=-2146233086

More information about this error may be available in the server error log.
```
### Screenshot

![2017-07-18 16_35_38-localhost_8080_kitchensink](https://user-images.githubusercontent.com/566463/28322747-309d2c20-6bd7-11e7-90b3-f0e8998b11de.png)

**Comment by Mihaiii** [comment]
Isn't this because `SampleWebsieTheme` changes values in the database?

**Comment by warpech** [comment]
It is reproducible without `SampleWebsiteTheme`. I have corrected the error and the screenshot.

**Comment by PatrykSzwer** [comment]
Done in #145. Closing.

**Comment by atifwaqar** [comment]
I still have the issue, any idea what am I doing wrong here?

![image](https://user-images.githubusercontent.com/4388707/29615604-d67e2740-880e-11e7-9d45-46bdde9b717c.png)

**Comment by atifwaqar** [comment]
@PatrykSzwer  @un-tone

**Comment by un-tone** [comment]
That file is located in `/websiteprovider/surfaces/DefaultSurface.html` path. You have to update surfaces' URIs

**Comment by un-tone** [comment]
@PatrykSzwer maybe you have ready steps how to do update the URIs fast?

**Comment by PatrykSzwer** [comment]
We currently don't have any quicker way than just do `/resetdata` or manually changing that in DB.

**Comment by atifwaqar** [comment]
Hi guys, 
Sorry I totally forgot to follow up on this. Mujahid helped me fix this issue, we just had to copy paste a folder on the path `\Website\src\WebsiteEditor\wwwroot\WebsiteEditor\surfaces` with following html files.

![image](https://user-images.githubusercontent.com/4388707/30027786-aa8049e8-9182-11e7-95c6-268fbc94636e.png)

**Comment by un-tone** [comment]
@atifwaqar I'd just remind that in this case you should not forget to update these files from `\Website\src\WebsiteProvider\wwwroot\WebsiteProvider\surfaces` each time when you updating your Website* app instances.
